New parent-controlled fuse to allow names to extend their own expiry
ensdomains/ens-contracts pull request #173
Opened 2022-12-21 16:27 UTC by serenae-fansubs

Just an idea I had. Feel free to close if this doesn't make sense or introduces other issues.

Reserves a new parent-controlled fuse that allows owners of subnames to extend their own expiry.

This gives a first-class easy way to allow perpetual "unruggable" renewals for subname owners, without needing to use some other contract to indirectly call setChildFuses.

This will not be burned on .eth 2LDs, and it doesn't matter there anyway since the expiry will always inherit from the registrar in that case.

2022-12-30 12:07 UTC, nxt3d commented
I have also been researching ways to solve this issue and have come up with some potential solutions. One idea I came up with is to use an external controller called a "lightcontroller." The lightcontroller only has the authority to extend the name and nothing else. The parent name owner can assign the lightcontroller to a subname, which is then guaranteed to be able to be renewed indefinitely according to the conditions set by the lightcontroller. This system allows for flexible management of subname renewals through smart contracts. Lightcontrollers can have administrator functionality or not. For example, a marketplace could create its own lightcontroller to manage renewal prices and royalties for individual names. Alternatively, it could be possible to implement different prices for different length names or have other complex pricing schemes.

https://github.com/nxt3d/ens-contracts/blob/NameWrapper-LightControllers/contracts/wrapper/LightcontrollerService.sol

2022-12-30 13:25 UTC, serenae-fansubs commented
I think that's another great potential solution! I feel that anything that involves needing to approve a separate contract is going to be too confusing and too much work for the average person.

This PR however, is pretty dead-simple, and builds it directly into the NameWrapper. This may not have made sense in previous iterations, but now that we have the concept of **parent-controlled fuses**, I think this would be a perfect example of a "perk" that a parent can allow for a child name.

And all they need to do is burn this one fuse on the child!

I think your lightcontroller idea is useful in general for other things though. Of course, if someone is spinning up their own subdomain registrar, all that stuff you describe is going to be built into the registrar contract itself. No need for a separate controller, unless you want to separate out knobs to tweak pricing/etc the way the .eth registrar does.

2023-01-03 16:30 UTC, jefflau commented
This is interesting. It creates an easy way to make a name a 'forever' name. The parent name would need to expire to unburn this fuse so you could almost guarantee you'll always have control over the name. We could make it so it isn't restricted to the owner of the name, but the parent + owner w/ fuse burnt can both call this function.

2023-01-03 17:17 UTC, serenae-fansubs commented
Good point!

I updated the PR so that the parent owner can call `setExpiry` too.

2023-01-03 19:33 UTC, Arachnid commented
This looks like a good idea to me.

2023-01-04 20:16 UTC, jefflau commented
@serenae-fansubs As a next step can you write some test cases for this PR?

2023-01-04 20:41 UTC, jefflau requested changes

2023-01-04 20:41 UTC, jefflau commented on contracts/wrapper/NameWrapper.sol
> +        _setFuses(node, owner, fuses, expiry);
I think we can call `_setData` directly as we won't be burning any fuses

2023-01-04 23:53 UTC, serenae-fansubs commented
@jefflau Done!

2023-01-10 04:53 UTC, jefflau commented
I think this is ready.  I think it may make sense to split the events now to event `ExpiryExtended()` and FusesSet()`, and call both events in `setChildFuses()`. What do you think @Arachnid?

2023-01-11 04:54 UTC, merged

2023-01-11 04:55 UTC, jefflau commented
I've merged this PR into a local branch so I can make the above event changes. Please refer to it here:

https://github.com/ensdomains/ens-contracts/pull/184