Fix UniversalResolver CCIP-read issues
ensdomains/ens-contracts pull request #209
Opened 2023-02-20 01:35 UTC by TateB

issues fixed:
- `_resolveCallback()` was incorrectly using the loop index as a reference when checking for an offchain lookup failure, instead of the offchain lookup index. this lead to occasionally out-of-bounds solidity errors.
- responses from resolvers that don't implement the `ExtendedResolver` interface would be incorrectly unwrapped from `bytes`, which lead to errors.

2023-02-20 01:39 UTC, Arachnid approved these changes

2023-02-20 11:37 UTC, jefflau requested changes

2023-02-20 11:37 UTC, jefflau commented on contracts/utils/UniversalResolver.sol
>          returns (
Add result to natspec

2023-02-21 01:51 UTC, jefflau approved these changes

2023-02-21 04:38 UTC, merged