create addr only dnssec compatible resolver
ensdomains/ens-contracts pull request #268
Opened 2023-08-04 13:57 UTC by mdtanrikulu

2023-08-07 14:27 UTC, Arachnid commented on contracts/resolvers/profiles/ExtendedDNSResolver.sol
> +                if (coinType != COIN_TYPE_ETH) return abi.encode(address(0));
This should return a 0-length string, not a string of zeroes.

2023-08-07 14:28 UTC, Arachnid requested changes
One change, otherwise LGTM.

2023-08-10 14:58 UTC, Arachnid approved these changes

2023-08-22 13:14 UTC, mdtanrikulu commented
closing this branch, since we cherry picked all to #272

2023-08-22 13:14 UTC, closed without merging