feature(crosschain resolver): simplify reverse resolver
ensdomains/ens-contracts pull request #379
Opened 2024-08-06 00:05 UTC by TateB

changes:
- removed `setText*` functions on `SignatureReverseResolver`
- removed versionable records on `SignatureReverseResolver`
  - no longer required without `setText`, since there is only a single field to set
- removed `clearRecords*` functions on `SignatureReverseResolver`
  - no longer required without record versioning
- added ts tests

2025-04-07 15:56 UTC, Arachnid approved these changes

2025-04-07 19:43 UTC, adraffy approved these changes

2025-04-14 12:14 UTC, Arachnid requested changes

2025-04-14 12:14 UTC, Arachnid commented on contracts/reverseRegistrar/L1ReverseResolver.sol
> +            (address addr, ) = HexUtils.hexToAddress(
This needs to capture the second return value, `value` ,and throw `Unreachable(name)` if it's not a valid hex string.

2025-04-14 12:14 UTC, Arachnid approved these changes
Approving so the current PR can be merged to reflect deployed code.

2025-04-15 21:09 UTC, adraffy commented on contracts/reverseRegistrar/L1ReverseResolver.sol
> +    IGatewayVerifier immutable verifier;
This should be public

2025-04-15 21:09 UTC, adraffy commented on contracts/reverseRegistrar/L1ReverseResolver.sol
> +    address immutable target;
This should be public, and maybe `l2Registrar` or `registrarAddress`?

2025-04-15 21:09 UTC, adraffy commented on contracts/reverseRegistrar/L1ReverseResolver.sol
> +    error UnknownResolverProfile(bytes4 selector);
Can we use `UnreachableName` and `UnsupportedResolverProfile` instead?

https://github.com/adraffy/ensips/blob/ensip/ensip-10-errors/ensips/x.md

2025-04-15 21:09 UTC, adraffy commented on contracts/reverseRegistrar/L1ReverseResolver.sol
> +            if (isNamespaceCall) return abi.encode(abi.encodePacked(target));
Should we parse out `coinType` from the reverse name, and then only answer if the queried coin type matches?  Otherwise, this supplies an EVM address for all coin types.

2025-04-15 21:09 UTC, adraffy commented on contracts/reverseRegistrar/L1ReverseResolver.sol
> +            super.supportsInterface(interfaceId);
I think we should define an interface id that indicates that this is "recursive CCIP-read safe" so this contract can be called directly by the UR.

Maybe `0xe6894ef0`  ?  I'm not sure if there's a better derivation scheme for functionless interfaces...
* https://adraffy.github.io/keccak.js/test/demo.html#algo=evm&s=eip3668.wrappable&escape=1&encoding=utf8
* https://www.4byte.directory/signatures/?bytes4_signature=0xe6894ef0

2025-04-16 03:31 UTC, TateB commented on contracts/reverseRegistrar/L1ReverseResolver.sol
> +            if (isNamespaceCall) return abi.encode(abi.encodePacked(target));
if `isNamespaceCall` is true, it's querying with the reverse namespace of this resolver itself (i.e. `coinType` will always be correct)

2025-06-11 07:52 UTC, merged

2026-02-15 13:08 UTC, meny3437-blip reviewed
future @meny3437-blip