NameWrapper upgrade
ensdomains/ens-contracts pull request #70
Opened 2022-05-04 04:09 UTC by nxt3d

Here is my PR for upgrade functionality for the NameWrapper. In the future it will be possible to deploy an upgraded NameWrapper contract, set the upgrade address to the contract, and allow all wrapped names to migrate. 

Even if the CANNOT_UNWRAP fuse is burnt for a wrapped name, it would still be possible to migrate the name to the upgraded NameWrapper contract. The fuses and resolver records of the wrapped name will be passed to the upgraded contract without changes.

2022-05-09 22:36 UTC, Arachnid requested changes

2022-05-09 22:36 UTC, Arachnid commented on contracts/wrapper/NameWrapper.sol
> +    }
```suggestion
    /**
     * @notice Upgrades a domain to a new name wrapper version.
     * @dev Can be called by the owner or an authorised caller
     * @param name The name to upgrade, in DNS format
     * @param wrappedOwner owner of the name in this contract
     */

    function upgrade(
        bytes calldata name,
        address wrappedOwner
    ) public {

        if (address(upgradeContract) == address(0)){
            revert CannotUpgrade();
        }

        (bytes32 labelhash, uint offset) = name.readLabel(0);
        bytes32 parentNode = name.namehash(offset);
        bytes32 node = _makeNode(parentNode, labelhash);

        if (!isTokenOwnerOrApproved(node, msg.sender)){
            revert Unauthorised(node, msg.sender);
        }

        address resolver = ens.resolver(node);

        (uint96 fuses,,) = getFuses(node);

        if(parentNode == ETH_NODE) {
            upgradeContract.wrapETH2LD(name[1:offset], wrappedOwner, fuses, resolver);
        } else {
            upgradeContract.wrap(name, wrappedOwner, fuses, resolver);
        }

        // burn token and fuse data
        _burn(uint256(node));
    }
```

2022-05-09 22:36 UTC, Arachnid commented on contracts/wrapper/NameWrapper.sol
> +error ZeroAddress();
```suggestion
error CannotUpgrade();
```

`ZeroAddress` doesn't explain the problem - the problem is that upgrades are not permitted at this time.

2022-05-19 06:46 UTC, jefflau requested changes
We are allowing the owner and authorised operators to upgrade, so we should also test that an account that has been approved by the owner can also `upgrade()` and `upgradeETH2LD()`

2022-05-19 06:46 UTC, jefflau commented on test/wrapper/NameWrapper.js
> +      ).to.be.reverted
Can we expect() the exact revert error

2022-05-19 06:46 UTC, jefflau commented on contracts/wrapper/NameWrapper.sol
> +error CannotUpgrade();
Could this be something more descriptive? If `upgrade()` reverts, I assume it probably cannot be upgraded. Maybe something like `InvalidUpgradeAddress(address address)` would be better.

2022-05-19 06:46 UTC, jefflau commented on test/wrapper/NameWrapper.js
> +      await expect(
Exact revert error

2022-05-20 03:48 UTC, nxt3d commented
> 

I added two more tests

2022-05-20 03:59 UTC, Arachnid approved these changes

2022-05-20 04:01 UTC, merged